### PR TITLE
Add flag in fast reindexer to delete filtered docs

### PR DESCRIPTION
**Pull request by esoergel**
@czue @dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
looks good to me. confirming it works?

**Comment by esoergel** [comment]
It worked locally, at least.  Here's what I did to test:
 * commented out the `document_filter` from OpmUserFluff
 * ran `$ dj ptop_fast_reindex_fluff opm custom.opm.models.OpmUserFluffPillow --bulk` to make sure to get all documents back in (including stuff that I'll later want to filter).
 * ran `>>> len(UserSqlData().get_data())` (output was 446 (IIRC) and contained users with no awc specified)
 * uncommented `document_filter`
 * ran `$ dj ptop_fast_reindex_fluff opm custom.opm.models.OpmUserFluffPillow --bulk --delete-filtered` to delete the documents not matching the filter.
 * ran `>>> len(UserSqlData().get_data())` (output was 413 and no longer contained users without awcs)

**Comment by esoergel** [comment]
@snopoke FYI.  This is an addition to the `ptop_fast_reindex_fluff` command for instances where you add or modify a fluff document's `document_filter` and want the db (and sqlagg table if that applies) updated to include the new restriction.

**Comment by snopoke** [comment]
:+1:

**Pull request merged**
