### PR TITLE
upgrade sqlalchemy to 1.0.9

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by snopoke** [comment]
Due to the order in which travis does the installs (requirements then setup) the final version of SQLAlchemy is whatever is in setup.py. Seems like we should either just drop requirements.txt or use this approach: http://stackoverflow.com/a/16624700

**Comment by nickpell** [comment]
The comments in the stackoverflow article seem to discourage that type of usage, as does https://github.com/pypa/pip/issues/2286.  How easy would it be to drop requirements.txt?

**Comment by czue** [comment]
it's a big pain because of the pillowtop dependency (you have to push a new version of pillowtop to pypi anytime the api changes). 

We could just remove everything but the git references from `requirements.txt` since that's the only reason they're there.

**Comment by czue** [comment]
or we could subtree merge this into pillowtop :grin:

**Pull request merged**
