### PR TITLE
small changes to allow fluff pillows to lazily load documents

### PR DESCRIPTION
**Pull request by czue**
:blowfish: 

@benrudolph @snopoke 

goes with https://github.com/dimagi/commcare-hq/pull/9432 and https://github.com/dimagi/pillowtop/pull/190

### CODE REVIEW

**Comment by benrudolph** [comment]
:+1: once tests pass

**Comment by czue** [comment]
ugh, because of the submodule dependency on pillowtop tests aren't going to pass until https://github.com/dimagi/pillowtop/pull/190 gets merged (or I can manually update requirements to point at that commit and then revert that change after but that feels like unnecessary churn)

maybe you can merge that and then I'll kick the build?

**Comment by benrudolph** [comment]
:boot:ed

**Comment by czue** [comment]
:hankey: fixing

**Comment by czue** [comment]
whoops, turned out I already had setup a way to pin ptop (https://github.com/dimagi/fluff/commit/e77b8979d5a283f3102986f4d64b748cb2a5a147).

also there was a legit bug (https://github.com/dimagi/fluff/commit/e64998473dc9e6e48cdcd2bd5c622fb357af1146)

hooray tests!

**Comment by czue** [comment]
now :white_check_mark:

**Pull request merged**
